const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')
const assert = require('node:assert/strict')

const root = path.resolve(__dirname, '../..')

test('registers and renders the action preview swiper with shared part filters', () => {
  const pages = JSON.parse(fs.readFileSync(path.join(root, 'pages.json'), 'utf8'))
  assert.ok(pages.pages.some((page) => page.path === 'pages/preview/index'))
  assert.equal(pages.tabBar.list.at(-1).pagePath, 'pages/preview/index')

  const source = fs.readFileSync(path.join(__dirname, 'index.vue'), 'utf8')
  assert.match(source, /<swiper/)
  assert.match(source, /@change="handleSwiperChange"/)
  assert.match(source, /getTrainPartTabs/)
  assert.match(source, /openPartEditor/)
  assert.match(source, /getExerciseGifSources/)
  assert.match(source, /instructions_zh/)
  assert.match(source, /previewSlides/)
  assert.match(source, /windowStart/)
  assert.match(source, /if \(this\.catalog\.length\) return/)
  assert.match(source, /searchText/)
  assert.match(source, /searchResults/)
  assert.match(source, /jumpToExercise/)
  assert.match(source, /placeholder="搜索当前部位动作"/)
  assert.match(source, /@longpress="confirmRemovePart\(tab\)"/)
  assert.match(source, /togglePartTarget/)
  assert.match(source, /:scroll-into-view="activePartTabId"/)
  assert.match(source, /:id="'part-tab-' \+ index"/)
  assert.match(source, /matchesPart\(parts, item, this\.activePart\)/)
  assert.doesNotMatch(source, /matchesTrainPart\(/)
})
