const fs = require('node:fs')
const path = require('node:path')

const ROOT = path.resolve(__dirname, '..')
const INPUT_PATH = path.join(ROOT, 'exercises-dataset-main', 'data', 'exercises.json')
const OUTPUT_PATH = path.join(ROOT, 'static', 'json', 'clean_fitness_zh.json')
const BUNDLED_OUTPUT_PATH = path.join(ROOT, 'data', 'clean_fitness_zh.js')

const TARGET_MAP = {
  pectorals: '胸',
  'serratus anterior': '胸',
  delts: '肩',
  'upper back': '背',
  lats: '背',
  spine: '背',
  traps: '背',
  'levator scapulae': '背',
  glutes: '腿',
  quads: '腿',
  hamstrings: '腿',
  calves: '腿',
  adductors: '腿',
  abductors: '腿',
  'cardiovascular system': '有氧'
}

const PHRASE_MAP = {
  'all fours squat stretch': '四肢跪姿深蹲拉伸',
  'ankle circles': '脚踝绕圈',
  'balance board': '平衡板训练',
  'assisted parallel grip pull-up': '辅助平行握引体向上',
  'standing chin-up': '站姿反握引体向上',
  'band kneeling single arm pulldown': '弹力带跪姿单臂下拉',
  'barbell good morning': '杠铃早安式',
  'barbell hip bridge': '杠铃臀桥',
  'barbell pullover': '杠铃仰卧臂屈伸',
  'dumbbell shoulder press': '哑铃肩部推举',
  'dumbbell lateral raise': '哑铃侧平举',
  'dumbbell front raise': '哑铃前平举',
  'cable triceps pushdown': '绳索肱三头肌下压',
  'standing calf raise': '站姿提踵',
  'seated calf raise': '坐姿提踵',
  'walking lunge': '行走弓步',
  'reverse lunge': '反向弓步',
  'bulgarian split squat': '保加利亚分腿深蹲',
  'kettlebell swing': '壶铃摆动',
  'smith machine squat': '史密斯机深蹲',
  'smith machine bench press': '史密斯机卧推',
  'smith machine shoulder press': '史密斯机肩部推举',
  'chin-up': '反握引体向上',
  'chin up': '反握引体向上',
  'good morning': '早安式',
  'behind the neck press': '颈后推举',
  'behind neck press': '颈后推举',
  'seated good morning': '坐姿早安式',
  'barbell thruster': '杠铃推蹲',
  'sled push': '雪橇推行',
  'sled drag': '雪橇拖行',
  'assisted hanging knee raise': '辅助悬垂举膝',
  'assisted chest dip': '辅助胸部双杠臂屈伸',
  'incline dumbbell press': '上斜哑铃推举',
  'decline dumbbell press': '下斜哑铃推举',
  'flat dumbbell press': '平板哑铃推举',
  'barbell bench press': '杠铃卧推',
  'dumbbell bench press': '哑铃卧推',
  'close grip bench press': '窄握卧推',
  'lat pulldown': '高位下拉',
  'cable crossover': '绳索夹胸',
  'face pull': '绳索面拉',
  'pull up': '引体向上',
  'chin up': '反握引体向上',
  'barbell squat': '杠铃深蹲',
  'front squat': '前蹲',
  'hack squat': '哈克深蹲',
  'romanian deadlift': '罗马尼亚硬拉',
  'stiff leg deadlift': '直腿硬拉',
  'single leg deadlift': '单腿硬拉',
  'jumping rope': '跳绳',
  'jump rope': '跳绳',
  'treadmill running': '跑步机跑步',
  'treadmill walking': '跑步机走路',
  'burpee': '波比跳',
  'sit-up': '仰卧起坐',
  'sit up': '仰卧起坐',
  'push-up': '俯卧撑',
  'push up': '俯卧撑',
  'step-up': '台阶上步',
  'step up': '台阶上步'
}

const TOKEN_MAP = {
  '3/4': '四分之三',
  all: '全程',
  fours: '四肢跪姿',
  squad: '深蹲',
  ankle: '脚踝',
  ankles: '脚踝',
  circles: '绕圈',
  up: '向上',
  arms: '手臂',
  arm: '手臂',
  apart: '分开',
  circular: '环绕',
  toe: '脚趾',
  touch: '触碰',
  astride: '跨步',
  jumps: '跳跃',
  and: '和',
  forth: '前后',
  on: '在',
  exercise: '训练',
  ball: '球',
  lever: '杠杆',
  pec: '胸肌',
  pecs: '胸肌',
  pectoralis: '胸大肌',
  pectoralismajor: '胸大肌',
  major: '主要',
  stability: '稳定',
  stable: '稳定',
  parallel: '平行握',
  prone: '俯卧',
  supine: '仰卧',
  backward: '向后',
  forwards: '向前',
  balance: '平衡',
  board: '板',
  fixed: '固定',
  underhand: '反握',
  overhand: '正握',
  with: '配合',
  over: '过',
  to: '至',
  smith: '史密斯',
  chin: '下巴',
  good: '早安式',
  morning: '早安式',
  sled: '雪橇',
  drag: '拖行',
  delt: '三角肌',
  goodmorning: '早安式',
  skier: '滑雪者',
  speed: '速度',
  knees: '膝盖',
  behind: '后方',
  the: '',
  a: '',
  catch: '接抓',
  head: '头部',
  gluteus: '臀肌',
  quads: '股四头肌',
  adductor: '内收肌',
  pendlay: '潘德雷式',
  bradford: '布拉德福德式',
  bradfordrocky: '布拉德福德式',
  basic: '基础',
  battlingropes: '战绳',
  battling: '战斗',
  ropes: '绳',
  variation: '变式',
  stirrups: '马镫',
  thibaudeaukayak: '皮划艇式',
  hands: '双手',
  cambered: '曲杆',
  chair: '椅式',
  of: '的',
  curtsey: '屈膝弓步',
  deep: '深度',
  around: '环绕',
  burpee: '波比跳',
  breeding: '夹合',
  twistedflyes: '旋转飞鸟',
  femoral: '股骨',
  support: '支撑',
  rangeofmotion: '活动范围',
  towel: '毛巾',
  down: '向下',
  stabilization: '稳定',
  butterfly: '蝴蝶式',
  yoga: '瑜伽',
  pose: '姿势',
  revers: '反向',
  turkishget: '土耳其起身',
  handsreversedclasped: '反握交扣双手',
  betweenknees: '双膝之间',
  tireflip: '翻轮胎',
  tire: '轮胎',
  flip: '翻转',
  left: '左侧',
  right: '右侧',
  hook: '勾拳',
  monsterwalk: '怪兽走',
  monster: '怪兽',
  walk: '走步',
  piratesupper: '海盗式上身',
  farmerswalk: '农夫走',
  farmers: '农夫',
  seesaw: '跷跷板',
  rocking: '摇摆',
  rockingfrog: '摇摆青蛙式',
  peroneals: '腓骨肌',
  male: '男',
  guillotine: '断头台式',
  withoutstretched: '不伸展',
  outsit: '外坐',
  astaircase: '楼梯式',
  skinthecat: '皮肤猫式',
  skin: '皮肤',
  cat: '猫式',
  elevator: '电梯式',
  flutter: '扑动',
  kicks: '踢腿',
  isometric: '等长',
  wipers: '雨刷式',
  skater: '滑冰者',
  hops: '跳跃',
  sphinx: '狮身人面式',
  upward: '向上',
  facing: '面对',
  dog: '狗式',
  bradfordrocky: '布拉德福德式',
  battlefield: '战绳',
  lat: '背阔肌',
  inverse: '反向',
  resistance: '阻力',
  roller: '滚轮',
  inverted: '倒立',
  pov: '视角',
  adduction: '内收',
  abduction: '外展',
  lower: '下部',
  upper: '上部',
  knees: '膝盖',
  muscle: '肌肉',
  palm: '掌心',
  hammer: '锤式',
  ups: '向上',
  suspended: '悬吊',
  self: '自体',
  ez: 'EZ杠',
  plyo: '增强式',
  hand: '手',
  attachment: '附件',
  withsupport: '带支撑',
  bosu: '半球平衡器',
  withtowel: '持毛巾',
  arnold: '阿诺德式',
  scapula: '肩胛骨',
  drop: '下落',
  behindhead: '脑后',
  double: '双',
  pushdown: '下压',
  sissy: '西西里式',
  thruster: '推蹲',
  crossovers: '夹胸',
  trainer: '训练器',
  pass: '传递',
  squatting: '深蹲',
  pistol: '手枪式',
  iron: '铁',
  vertical: '垂直',
  piriformis: '梨状肌',
  hyperextension: '背部伸展',
  hyper: '超伸展',
  flexor: '屈肌',
  cage: '架',
  extended: '伸展',
  gripless: '无握把',
  cuban: '古巴式',
  goblet: '高脚杯式',
  tap: '点触',
  deltoid: '三角肌',
  neck: '颈部',
  behindneck: '颈后',
  tennis: '网球',
  stationary: '固定',
  against: '抵住',
  flat: '平板',
  middle: '中部',
  half: '半程',
  outer: '外侧',
  dynamic: '动态',
  platformslide: '平台滑步',
  downwith: '下落并配合',
  pyramid: '金字塔',
  clap: '击掌',
  neutral: '中立握',
  stepmill: '爬楼机',
  unilateral: '单侧',
  contralateral: '对侧',
  staircase: '楼梯',
  plus: '加',
  clock: '时钟',
  planche: '俄式挺身',
  svend: '斯文德式',
  elevated: '抬高',
  horizontal: '水平',
  rangeofmotion: '活动范围',
  extendedrange: '大幅度',
  catch: '接抓',
  hip: '髋部',
  hips: '髋部',
  internal: '内旋',
  external: '外旋',
  rotation: '旋转',
  rotating: '旋转',
  low: '低位',
  high: '高位',
  two: '双腿',
  three: '三',
  under: '下方',
  both: '双侧',
  v: '变式',
  version: '版本',
  full: '完整',
  zercher: '泽奇尔式',
  goodmorning: '早安式',
  clean: '高翻',
  floor: '地板',
  bridge: '臀桥',
  jefferson: '杰弗逊式',
  lunge: '弓步',
  lifting: '提举',
  narrow: '窄距',
  stance: '站距',
  split: '分腿',
  twisting: '转体',
  pullover: '仰卧臂屈伸',
  rack: '架上',
  stiff: '直腿',
  bar: '杠',
  through: '穿越',
  y: 'Y型',
  floor: '地板',
  kneeling: '跪姿',
  sitting: '坐姿',
  squat: '深蹲',
  pike: '折刀式',
  plank: '平板支撑',
  mountain: '登山者',
  climber: '登山者',
  climbers: '登山者',
  running: '跑步',
  walking: '走步',
  walking: '走步',
  cycling: '骑行',
  cycle: '循环',
  rowing: '划船',
  rope: '绳',
  medicine: '药球',
  ball: '球',
  slam: '砸球',
  crawl: '爬行',
  bear: '熊爬',
  donkey: '驴踢',
  fire: '消防栓',
  hydrant: '消防栓',
  russian: '俄罗斯',
  twist: '转体',
  woodchop: '伐木',
  wood: '木',
  chop: '劈砍',
  reach: '触及',
  rotation: '旋转',
  rotational: '旋转',
  cross: '交叉',
  crossover: '交叉',
  kickback: '后踢',
  kickbacks: '后踢',
  kickback: '后踢',
  raise: '抬举',
  legraise: '抬腿',
  assisted: '辅助',
  alternate: '交替',
  alternating: '交替',
  archer: '弓箭手式',
  back: '后侧',
  band: '弹力带',
  barbell: '杠铃',
  bench: '卧推凳',
  bent: '屈曲',
  bike: '自行车',
  bodyweight: '自重',
  body: '身体',
  box: '箱式',
  cable: '绳索',
  calf: '小腿',
  calves: '小腿',
  chest: '胸部',
  close: '窄握',
  curl: '弯举',
  curls: '弯举',
  deadlift: '硬拉',
  decline: '下斜',
  diamond: '钻石式',
  dip: '臂屈伸',
  dips: '臂屈伸',
  dumbbell: '哑铃',
  eccentric: '离心',
  extension: '伸展',
  face: '面部',
  fly: '飞鸟',
  flys: '飞鸟',
  forward: '向前',
  front: '前侧',
  glute: '臀部',
  glutes: '臀部',
  grip: '握法',
  hack: '哈克',
  hamstring: '大腿后侧',
  hamstrings: '大腿后侧',
  hanging: '悬垂',
  incline: '上斜',
  jack: '开合跳',
  jerk: '挺举',
  jump: '跳跃',
  jumping: '跳跃',
  kettlebell: '壶铃',
  kick: '后踢',
  knee: '膝',
  lateral: '侧向',
  leg: '腿部',
  legs: '腿部',
  lift: '提拉',
  lying: '仰卧',
  machine: '器械',
  military: '军式',
  one: '单',
  overhead: '过顶',
  press: '推举',
  pull: '拉',
  pulldown: '下拉',
  push: '推',
  raise: '抬举',
  raises: '抬举',
  rear: '后束',
  reverse: '反向',
  romanian: '罗马尼亚',
  row: '划船',
  rows: '划船',
  run: '跑步',
  running: '跑步',
  seated: '坐姿',
  shoulder: '肩部',
  shoulders: '肩部',
  shrug: '耸肩',
  side: '侧向',
  single: '单侧',
  skip: '跳绳',
  snatch: '抓举',
  squat: '深蹲',
  standing: '站姿',
  step: '台阶',
  straight: '直腿',
  stretch: '拉伸',
  sumo: '相扑式',
  supported: '支撑',
  swing: '摆动',
  throw: '抛投',
  toes: '脚趾',
  torso: '躯干',
  triceps: '肱三头肌',
  upright: '直立',
  wall: '靠墙',
  weighted: '负重',
  wide: '宽握',
  wrist: '腕部'
}

function cleanText(value) {
  return typeof value === 'string' ? value.replace(/\s+/g, ' ').trim() : ''
}

function normalizeKey(value) {
  return cleanText(value).toLowerCase().replace(/[’']/g, '').replace(/\s+/g, ' ')
}

function translateName(name) {
  const original = cleanText(name)
  const key = normalizeKey(original)
  if (!key) return ''

  for (const [phrase, translation] of Object.entries(PHRASE_MAP).sort((a, b) => b[0].length - a[0].length)) {
    if (key === phrase) return translation
  }

  const withoutGender = key.replace(/\s*\((male|female)\)\s*/g, ' ')
  const tokens = withoutGender.match(/[a-z]+|\d+(?:\/\d+)?|°|[^\s]/gi) || []
  const translated = tokens.map((token) => {
    const lower = token.toLowerCase()
    if (TOKEN_MAP[lower]) return TOKEN_MAP[lower]
    if (/^\d/.test(lower) || lower === '°') return lower
    if (/^[^a-z]+$/i.test(token)) return token
    return token
  }).join('')

  return translated || `${original}动作`
}

function normalizeExercise(item) {
  if (!item || typeof item !== 'object') return null
  const targetPart = TARGET_MAP[normalizeKey(item.target)]
  const id = cleanText(item.id)
  const mediaId = cleanText(item.media_id)
  const nameZh = cleanText(item.name_zh) || translateName(item.name)
  const instructionsZh = cleanText(item.instructions_zh) || cleanText(item.instructions && item.instructions.zh)

  if (!id || !targetPart || !mediaId || !nameZh || !instructionsZh) return null

  return {
    id,
    name_zh: nameZh,
    target: targetPart,
    media_id: mediaId,
    instructions_zh: instructionsZh
  }
}

function cleanExercises(input) {
  if (!Array.isArray(input)) throw new TypeError('exercises.json 必须是数组')
  const seen = new Set()
  return input.map(normalizeExercise).filter((item) => {
    if (!item || seen.has(item.id)) return false
    seen.add(item.id)
    return true
  })
}

function main() {
  const input = JSON.parse(fs.readFileSync(INPUT_PATH, 'utf8'))
  const output = cleanExercises(input)
  fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true })
  fs.mkdirSync(path.dirname(BUNDLED_OUTPUT_PATH), { recursive: true })
  fs.writeFileSync(OUTPUT_PATH, `${JSON.stringify(output, null, 2)}\n`, 'utf8')
  fs.writeFileSync(BUNDLED_OUTPUT_PATH, `export default ${JSON.stringify(output)}\n`, 'utf8')
  const counts = output.reduce((result, item) => {
    result[item.target] = (result[item.target] || 0) + 1
    return result
  }, {})
  console.log(`已生成 ${path.relative(ROOT, OUTPUT_PATH)}，共 ${output.length} 条`)
  console.log(counts)
}

if (require.main === module) main()

module.exports = {
  TARGET_MAP,
  cleanExercises,
  normalizeExercise,
  translateName
}
