const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')
const assert = require('node:assert/strict')

const root = path.resolve(__dirname, '../..')

test('enables pull-to-refresh and reloads training records', () => {
  const pages = JSON.parse(fs.readFileSync(path.join(root, 'pages.json'), 'utf8'))
  const trainPage = pages.pages.find((page) => page.path === 'pages/train/index')
  assert.equal(trainPage.style.enablePullDownRefresh, true)

  const source = fs.readFileSync(path.join(root, 'pages/train/index.vue'), 'utf8')
  assert.match(source, /onPullDownRefresh\s*\(\)/)
  assert.match(source, /await this\.loadExercises\(\)/)
  assert.match(source, /uni\.stopPullDownRefresh\(\)/)
  assert.match(source, /partTabs/)
  assert.match(source, /openPartEditor/)
  assert.match(source, /saveCustomTrainParts/)
  assert.match(source, /\/pages\/settings\/index/)
  assert.match(source, /daily-set-check/)
  assert.match(source, /@click="toggleSetCheck\(set\.setNo\)"/)
  assert.match(source, /isDailySetChecked/)
  assert.doesNotMatch(source, /每日诺言诺语/)
  assert.doesNotMatch(source, /dailyQuote/)
  assert.match(source, /@longpress="confirmRemovePart\(tab\)"/)
  assert.match(source, /togglePartTarget/)
  assert.match(source, /:scroll-into-view="activePartTabId"/)
  assert.match(source, /:id="'part-tab-' \+ index"/)
  assert.match(source, /matchesPart\(parts, item, this\.activePart\)/)
  assert.doesNotMatch(source, /matchesTrainPart\(/)
  assert.match(source, /@dragstart="startExerciseDrag"/)
  assert.match(source, /saveExerciseOrder/)
  assert.match(source, /syncTodayTrainingCheckIn/)
  assert.match(source, /syncTrainingCheckIn/)
  assert.match(source, /await this\.syncTodayTrainingCheckIn\(\)/)
  assert.match(source, /title: '打卡同步失败'/)
})

test('isolates the drag handle from delete long-press and exposes a delayed drag state', () => {
  const source = fs.readFileSync(path.join(root, 'components/ExerciseCard.vue'), 'utf8')
  assert.match(source, /class="drag-button"/)
  assert.equal((source.match(/class="drag-bar"/g) || []).length, 3)
  assert.match(source, /@longpress="handleCardLongPress"/)
  assert.match(source, /@touchstart\.stop="beginHandlePress"/)
  assert.match(source, /@touchmove\.stop="handleHandleMove"/)
  assert.match(source, /@touchend\.stop="endHandlePress"/)
  assert.match(source, /suppressCardLongPress/)
  assert.match(source, /setTimeout\(/)
  assert.match(source, /is-dragging/)
  assert.match(source, /width: 96rpx/)
})
